#!/usr/bin/env bash

# --- Main Menu ---
CHOICE=$(echo -e "Close\nFullscreen\nFloat\nMove\nThrow" | vicinae dmenu -p "Action > ")

case "$CHOICE" in
    "Close")
        hyprctl dispatch "hl.dsp.window.close()"
        ;;
    "Fullscreen")
        hyprctl dispatch "hl.dsp.window.fullscreen_state({internal = 1, client = 1})"
        ;;
    "Float")
        hyprctl dispatch "hl.dsp.window.float({action = 'toggle'})"
        ;;
    "Move")
        # Generates numbers 1-20
        WORKSP=$(seq 1 20 | vicinae dmenu -W 300 -H 600 -p "Move > ")

        if [[ -n "$WORKSP" ]]; then
            hyprctl dispatch "hl.dsp.window.move({workspace = '$WORKSP'})"
        fi
        ;;
    "Throw")
        # Generates numbers 1-20
        WORKSP=$(seq 1 20 | vicinae dmenu -W 300 -H 600 -p "Throw > ")

        if [[ -n "$WORKSP" ]]; then
            hyprctl dispatch "hl.dsp.window.move({workspace = '$WORKSP', silent = true})"
        fi
        ;;
esac
