#!/usr/bin/env bash

CURRENT=$(hyprctl -j activeworkspace | jq -r '.layout')

if [ "$CURRENT" = "dwindle" ]; then
  hyprctl eval "hl.dispatch(hl.dsp.layout('swapwithmaster master'))"
  hyprctl eval "hl.config({general={layout='master'}})"
else
  hyprctl eval "hl.config({general={layout='dwindle'}})"
fi
