#!/usr/bin/env bash

CURRENT_STATE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')

case "$1" in
    on)
        if [ "$CURRENT_STATE" = 1 ]; then
            hyprctl --batch "\
                keyword animations:enabled 0;\
                keyword animation borderangle,0; \
                keyword decoration:shadow:enabled 0;\
                keyword decoration:blur:enabled 0;\
                keyword decoration:fullscreen_opacity 1;\
                keyword general:gaps_in 0;\
                keyword general:gaps_out 0;\
                keyword general:border_size 1;\
                keyword decoration:rounding 0"
            hyprctl notify 1 5000 "rgb(40a02b)" "Powersave mode [ON]"
        fi
        ;;
    off)
        if [ "$CURRENT_STATE" = 0 ]; then
            hyprctl reload
            hyprctl notify 1 5000 "rgb(d20f39)" "Powersave mode [OFF]"
        fi
        ;;
    *)
        echo "Usage: $0 {on|off}"
        exit 1
        ;;
esac

exit 0
