#!/usr/bin/env bash

set -e

CUR_MON=$(hyprctl activeworkspace -j | jq -r '.monitorID')
MONS=($(hyprctl monitors -j | jq -r '.[].id'))

if [ "${#MONS[@]}" -ne 2 ]; then
  exit 0
fi

if [ "${MONS[0]}" = "$CUR_MON" ]; then
  TARGET="${MONS[1]}"
else
  TARGET="${MONS[0]}"
fi

hyprctl dispatch focusmonitor "$TARGET"
