#!/usr/bin/env bash
ANIMS=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
if [ "$ANIMS" = 1 ]; then
  hyprctl --batch "\
    keyword animations:enabled 0;\
    keyword animation borderangle,0"
  hyprctl notify 1 5000 "rgb(40a02b)" "Animations OFF"
else
  hyprctl reload
  hyprctl notify 1 5000 "rgb(d20f39)" "Animations ON"
fi
