#!/usr/bin/env bash

# Device names
TOUCH_TOP="ingenic-gadget-serial-and-keyboard-touchscreen-top"
STYLUS_TOP="ingenic-gadget-serial-and-keyboard-stylus-top"

hyprctl keyword "device[$TOUCH_TOP]:output" "eDP-1"
hyprctl keyword "device[$STYLUS_TOP]:output" "eDP-1"

# Monitor is rotated 180 degrees (transform 2)
hyprctl keyword monitor "eDP-1,2880x1800@120,0x0,1.8,transform,2"

hyprctl keyword "device[$TOUCH_TOP]:transform" 2
hyprctl keyword "device[$STYLUS_TOP]:transform" 2

hyprctl keyword monitor "eDP-2,disable"
hyprctl keyword monitor "DP-1,disable"
hyprctl keyword monitor "DP-2,disable"
hyprctl keyword monitor "DP-3,disable"

hypr-powersave-mode off
